version: '2.2'
services:

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    environment:
      GOMAXPROCS: "4"
    mem_limit: 512m

  job-service:
    image: go-land/job-service:1.0.0
    ports:
      - "9090:8080"
    environment:
      MICRO_SERVER_ADDRESS: ":8080"
      CONSUL_PORT: "8500"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
    depends_on:
      - consul
    mem_limit: 128m
